### ISSUE TITLE
Support angles docker images latest tags

### ISSUE THREAD

**Issue by ruescar** [AnglesHQ/angles#14]
It would be useful to use `latest`  tag by default for angles and angles-ui images in compose file, in case you want to modify and rebuild locally those images:
```
image: angleshq/angles:${ANGLES_VERSION:-latest}
image: angleshq/angles-ui:${ANGLES_VERSION:-latest}
```
And also create `latest` tag in Docker Hub.

**Comment by snevesbarros** [comment]
done :)
