### ISSUE TITLE
unescaped quotes has resulted in quotes rendered as HTML entities &quot; in the downloaded HTML report

### ISSUE THREAD

**Issue by GaryTsang** [AnglesHQ/angles#76]
An example of the issue can be seen on the downloaded html report where you can see multiple occurances of `&quot;` for instance:
`<td class="PASS caps" colspan="100%"
            onclick="toggleElement(&quot;54982fa859de4f68Df0171932&quot;); this.classList.toggle(&quot;opened&quot;);">`

The quotes in this line is the culprit
https://github.com/AnglesHQ/angles/blob/47c9fc1e0f99c76edf85a3a06941dc5e43e7cf83/app/assets/report/index.pug#L123

**Comment by snevesbarros** [comment]
Merged. Thanks!
